services:
  - type: web
    name: qr-telegram-api
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y libzbar0
      pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
